### ISSUE TITLE
Window blinking when pressing Backspace

### ISSUE THREAD

**Issue by alvinseville7cf** [microsoft/terminal#10005]
### Windows Terminal version (or Windows build number)

10.0.19042.867

### Other Software

GitBash

### Steps to reproduce

Create new GitBash profile as follows:
```yml
            {
                "commandline": "\"C:\\Program Files\\Git\\bin\\bash.exe\" --cd-to-home",
                "fontSize": 14,
                "icon": "%PROGRAMFILES%\\Git\\mingw64\\share\\git\\git-for-windows.ico",
                "name": "GitBash (Windows 10)",
                "suppressApplicationTitle": false
            },
```
Open new GitBash tab in Windows Terminal and hold backspace.
![blinking](https://user-images.githubusercontent.com/42812113/116699604-1c3b2d80-aa09-11eb-9924-224236cb597e.gif)

### Expected Behavior

No blinking.

### Actual Behavior

Blinking while holding backspace. Besides I can't type anything while blinking is proceed.
