### ISSUE TITLE
Be able to configure or specify the font face for the selected font.

### ISSUE THREAD

**Issue by alexesba** [microsoft/terminal#11124]
# Be able to configure or specify the font face for the selected font. 
I would like to have an option to set the font face style similar or in the same way alacrity does it. 

```yml
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    family: Operator Mono

    # The `style` can be specified to pick a specific face.
    style: Book

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Operator Mono

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Operator Mono
  #
  #   # The `style` can be specified to pick a specific face.
    style: Book Italic

  # Point size
  size: 13
```

# Proposed technical implementation details (optional)
