### ISSUE TITLE
Try to link sources for public symbols since the source is on GH anyway

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#12443]
```
  - task: PowerShell@2
    displayName: Source Index PDBs
    inputs:
      filePath: build\scripts\Index-Pdbs.ps1
      arguments: -SearchDir '$(Build.SourcesDirectory)/appxsym-tmp' -SourceRoot '$(Build.SourcesDirectory)' -recursive -Verbose -CommitId $(Build.SourceVersion)
      errorActionPreference: silentlyContinue
```
?

_Originally posted by @miniksa in https://github.com/microsoft/terminal/pull/12441#discussion_r802155336_
