### ISSUE TITLE
Start new windows with predefined layout (wt -layout preset.yaml)

### ISSUE THREAD

**Issue by jeffrson** [microsoft/terminal#12583]
# Description of the new feature/enhancement

There is "persisted window layout" and there are subcommands (sp) to start a new windows with some layout. However, it's not really easy to have a new window with a specific layout.

This feature request asks to load some layout definition file like this (from https://zellij.dev/documentation/layouts.html):
```
tabs:
  - direction: Vertical
    parts:
      - direction: Horizontal
        parts:
          - direction: Vertical
          - direction: Vertical
      - direction: Horizontal
```
for instance via `wt -layout preset.yaml`.
The preset file can be enhanced further with profile name to load, starting directory, or even with a start command (eg, launch some additional task).

# Proposed technical implementation details (optional)
