### ISSUE TITLE
Default Windows Terminal language does not match the Windows UI Language

### ISSUE THREAD

**Issue by rgl** [microsoft/terminal#13920]
### Windows Terminal version

1.14.2282.0

### Windows build number

10.0.22000.856

### Steps to reproduce

Do a default Windows installation using `en-US`, e.g. from an autounattend.xml configured:

```xml
        <component name="Microsoft-Windows-International-Core-WinPE" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <SetupUILanguage>
                <UILanguage>en-US</UILanguage>
            </SetupUILanguage>
            <InputLocale>en-US</InputLocale>
            <SystemLocale>en-US</SystemLocale>
            <UILanguage>en-US</UILanguage>
            <UILanguageFallback>en-US</UILanguageFallback>
            <UserLocale>en-US</UserLocale>
        </component>
```

Modify the everything but the UI / Display Language to `pt-PT`. For [example, using ansible](https://github.com/rgl/my-windows-ansible-playbooks/blob/7fe4cac6f78aea29e402363559ac058f6bf19939/roles/base/tasks/main.yml#L71-L76):

```yaml
- name: Set region
  community.windows.win_region:
    location: 193           # Portugal (193). See https://docs.microsoft.com/en-us/windows/win32/intl/table-of-geographical-locations
    format: pt-PT           # date format, number format, etc.
    unicode_language: en-US # UI language.
    copy_settings: true
```

Reboot and start Windows Terminal.

### Expected Behavior

I expected the Windows Terminal to use the Windows UI / Display Language.

### Actual Behavior

As you can see by this image, the left hand side is showing Windows Terminal in Portuguese despite the fact that Windows UI / Display Language is configured as English:

![image](https://user-images.githubusercontent.com/43356/188267031-3352be06-e63a-44be-bdee-76ee3465cfb0.png)
